name: Check
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 22 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v3
    - uses: nanasess/setup-chromedriver@v1
      with:
        chromedriver-version: "106.0.5249.61"
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19.1
    - run: go run . check
      env:
        TZ: Asia/Jakarta
        TALENTA_EMAIL: ${{ secrets.TALENTA_EMAIL }}
        TALENTA_PASSWORD: ${{ secrets.TALENTA_PASSWORD }}
        LATITUDE: ${{ secrets.LATITUDE }}
        LONGITUDE: ${{ secrets.LONGITUDE }}

        
